# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    #新版本mysql驱动类当前版本：8.0.15
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root